//
//  SessionStore.swift
//  Daisy
//
//  Enumerates past recording sessions persisted on disk:
//      ~/Library/Containers/app.essazanov.Daisy/Data/Library/
//          Application Support/Daisy/Sessions/<ISO-timestamp>/
//          ├── microphone.caf
//          ├── system_audio.caf       (optional)
//          ├── screenshots/           (optional)
//          ├── transcript.md
//          └── summary.json           (optional)
//
//  Each session folder is parsed into a `StoredSession` value with the
//  YAML frontmatter from `transcript.md` providing title, locale, start
//  time, and duration. UI reads `SessionStore.shared.sessions`.
//

import Foundation
import Observation
import os

@Observable
@MainActor
final class SessionStore {
    static let shared = SessionStore()

    private(set) var sessions: [StoredSession] = []
    private(set) var isLoading = false
    private(set) var lastError: String?

    /// IDs of sessions whose summary is still being generated by a
    /// detached post-Stop task. Driven by `RecordingSession.stop()` —
    /// transcript.md is already on disk, but summary.json hasn't
    /// landed yet. UI surfaces (`SessionDetailView` skeleton, widget
    /// petal-amber pulse) consult this set to decide whether to
    /// render a placeholder vs. "no summary" vs. the actual content.
    /// Cleared by `finishGenerating(id:)` once `summary.json` is
    /// written and the matching `StoredSession` has been reloaded.
    private(set) var sessionsGenerating: Set<String> = []

    /// Folder name of the session CURRENTLY being recorded — set by
    /// `RecordingSession` at start. Used to avoid queueing the live folder
    /// for interrupted-recording recovery while its audio is still open.
    /// Every directory is now visible in the Library and refresh never
    /// deletes storage folders, including empty ones.
    var activeRecordingDirName: String?

    @ObservationIgnored
    private let log = Logger(subsystem: "app.essazanov.Daisy", category: "SessionStore")
    @ObservationIgnored
    private var refreshTask: Task<Void, Never>?

    // MARK: - Search index state
    //
    // Inverted token index (token → session IDs) used by
    // `sessionsMatching(_:in:)` to prefilter the substring search so a
    // keystroke doesn't re-scan every transcript in memory. Built
    // lazily on the first search, reconciled incrementally after store
    // changes. Lives on @MainActor with the rest of the store;
    // @ObservationIgnored so index churn never invalidates SwiftUI.
    @ObservationIgnored
    private var searchTokenIndex: [String: Set<String>] = [:]
    /// Per-session cached token sets + a cheap content stamp, so a
    /// refresh() that re-parses every folder doesn't force re-tokenizing
    /// unchanged sessions (tokenization is the expensive part).
    @ObservationIgnored
    private var searchTokenCache: [String: (stamp: Int, tokens: Set<String>)] = [:]
    /// Set whenever `sessions` is mutated; the next search reconciles.
    @ObservationIgnored
    private var searchIndexDirty = true

    private init() {}

    /// Re-scan the sessions folder. Cheap — typically <100 ms even for
    /// hundreds of sessions because we only read each transcript's
    /// frontmatter, not the full body.
    func refresh() async {
        // Coalesce concurrent refreshes.
        if let existing = refreshTask {
            await existing.value
            return
        }
        let task = Task { @MainActor in
            await performRefresh()
        }
        refreshTask = task
        await task.value
        refreshTask = nil
    }

    /// Keep an open Library in sync with folders created or removed in
    /// Finder. The full parser remains event-driven: this loop only reads a
    /// shallow directory fingerprint once per second and calls `refresh()`
    /// when that fingerprint changes. The task is owned by LibraryView and
    /// is cancelled automatically when the Library leaves the view tree.
    func monitorExternalChanges() async {
        var previous = await currentStorageFingerprint()
        while !Task.isCancelled {
            do {
                try await Task.sleep(for: .seconds(1))
            } catch {
                return
            }
            guard !Task.isCancelled else { return }
            let current = await currentStorageFingerprint()
            guard current != previous else { continue }
            previous = current
            await refresh()
            // Refresh may create the active `Daisy/Sessions` directory or
            // update a stale bookmark. Re-baseline after those side effects
            // so they don't cause a second redundant refresh.
            previous = await currentStorageFingerprint()
        }
    }

    private func currentStorageFingerprint() async -> String {
        var roots: [URL] = []
        var tickets: [SessionsFolder.AccessTicket] = []
        if let defaultRoot = try? Self.defaultSessionsDirectory() {
            roots.append(defaultRoot)
        }
        let configuredBases = ([SessionsFolder.resolveUserFolder()].compactMap { $0 }
            + SessionsFolder.resolveLegacyFolders())
        for base in configuredBases {
            guard let ticket = SessionsFolder.acquireAccess(to: base) else { continue }
            tickets.append(ticket)
            roots.append(SessionsFolder.sessionsDirectory(in: base))
        }
        defer { tickets.forEach { $0.release() } }

        var seen = Set<String>()
        let uniqueRoots = roots.filter {
            seen.insert($0.standardizedFileURL.path).inserted
        }
        return await Task.detached(priority: .utility) {
            Self.storageFingerprint(for: uniqueRoots)
        }.value
    }

    /// Stable, shallow snapshot of session-directory membership. Exposed to
    /// tests so the Finder-created-empty-folder regression stays covered.
    nonisolated static func storageFingerprint(for roots: [URL]) -> String {
        let fm = FileManager.default
        var lines: [String] = []
        for root in roots.sorted(by: { $0.path < $1.path }) {
            let rootValues = try? root.resourceValues(forKeys: [.contentModificationDateKey])
            let rootStamp = rootValues?.contentModificationDate?
                .timeIntervalSinceReferenceDate.bitPattern ?? 0
            lines.append("root|\(root.standardizedFileURL.path)|\(rootStamp)")

            let entries = (try? fm.contentsOfDirectory(
                at: root,
                includingPropertiesForKeys: [
                    .isDirectoryKey,
                    .creationDateKey,
                    .contentModificationDateKey
                ],
                options: [.skipsHiddenFiles, .skipsSubdirectoryDescendants]
            )) ?? []
            for entry in entries.sorted(by: { $0.lastPathComponent < $1.lastPathComponent }) {
                guard let values = try? entry.resourceValues(forKeys: [
                    .isDirectoryKey,
                    .creationDateKey,
                    .contentModificationDateKey
                ]), values.isDirectory == true else { continue }
                let created = values.creationDate?
                    .timeIntervalSinceReferenceDate.bitPattern ?? 0
                let modified = values.contentModificationDate?
                    .timeIntervalSinceReferenceDate.bitPattern ?? 0
                lines.append("dir|\(entry.lastPathComponent)|\(created)|\(modified)")
            }
        }
        return lines.joined(separator: "\n")
    }

    private func performRefresh() async {
        isLoading = true
        lastError = nil
        defer { isLoading = false }

        // Scan BOTH the default container location AND the user-
        // picked folder (if set). Old sessions don't get auto-moved
        // when the user changes the folder — they stay where they
        // were and History continues to list them.
        var roots: [(url: URL, ticket: SessionsFolder.AccessTicket?)] = []
        if let defaultDir = try? Self.defaultSessionsDirectory() {
            roots.append((defaultDir, nil))
        }
        let configuredBases = ([SessionsFolder.resolveUserFolder()].compactMap { $0 }
            + SessionsFolder.resolveLegacyFolders())
        var seenRootPaths = Set(roots.map { $0.url.standardizedFileURL.path })
        var inaccessibleConfiguredFolder = false
        for userBase in configuredBases {
            guard let ticket = SessionsFolder.acquireAccess(to: userBase) else {
                inaccessibleConfiguredFolder = true
                log.warning("Couldn't access configured sessions folder during scan: \(userBase.path, privacy: .private)")
                continue
            }
            let userSessionsDir = SessionsFolder.sessionsDirectory(in: userBase)
            // Only the active destination is touch-created. Previous roots
            // are read-only history sources and should not be recreated if
            // the user intentionally removed them.
            if let active = SessionsFolder.resolveUserFolder(),
               SessionsFolder.sameFolder(active, userBase) {
                try? FileManager.default.createDirectory(
                    at: userSessionsDir,
                    withIntermediateDirectories: true
                )
            }
            let normalized = userSessionsDir.standardizedFileURL.path
            if seenRootPaths.insert(normalized).inserted {
                roots.append((userSessionsDir, ticket))
            } else {
                ticket.release()
            }
        }
        defer {
            for root in roots { root.ticket?.release() }
        }

        guard !roots.isEmpty else {
            lastError = String(localized: "Couldn't resolve any sessions folder.")
            sessions = []
            searchIndexDirty = true
            return
        }

        // Heavy part OFF the MainActor. Directory enumeration + classify
        // (which reads transcript.md / summary.json / speakers.json per
        // session) used to run synchronously right here — with hundreds
        // of sessions, or a user folder on iCloud/network storage, that
        // froze the UI on every refresh (2026-07 audit, top finding).
        // The security-scope tickets acquired above stay alive across
        // this await (released by the defer at function exit), so the
        // detached scan reads under scope.
        let activeDirName = activeRecordingDirName
        let rootURLs = roots.map(\.url)
        let scan = await Task.detached(priority: .userInitiated) {
            Self.scanRoots(rootURLs, activeRecordingDirName: activeDirName)
        }.value
        let loaded = scan.loaded
        let interruptedToRecover = scan.interrupted
        let quitSavedToFinalize = scan.quitSaved
        // Most recent first. Session ids are directory names — the
        // ISO timestamps — so cross-folder collisions are essentially
        // impossible (two recordings starting at the same millisecond
        // would have to come from different installs of Daisy).
        sessions = loaded.sorted(by: { $0.startedAt > $1.startedAt })
        if inaccessibleConfiguredFolder {
            lastError = String(localized: "Daisy couldn't access one of your recordings folders. Choose it again in Settings to restore access.")
        }
        // Reconcile the search index lazily on the next search — the
        // per-session content stamp keeps that cheap for unchanged rows.
        searchIndexDirty = true

        // Best-effort recovery of interrupted recordings (audio on disk,
        // no transcript). Idempotent — recovery dedupes folders it's
        // already handling, and a recovered folder gains transcript.md so
        // it classifies `.valid` (not `.interrupted`) on the next scan.
        //
        // Deferred while a recording (or dictation) is live: recovery's
        // .full pass over a multi-hour archive would hold the Whisper
        // slot for minutes, stalling live windows and the dictation
        // paste (2026-07 audit В4 — "app looks frozen"). The refresh()
        // that runs right after Stop re-queues it.
        if !interruptedToRecover.isEmpty {
            if activeRecordingDirName == nil {
                InterruptedRecordingRecovery.shared.recover(interruptedToRecover)
            } else {
                log.info("Deferred interrupted-recovery of \(interruptedToRecover.count, privacy: .public) folder(s) — a recording is live")
            }
        }

        // Quit-saved sessions whose final pass never ran — offer (toast
        // with an explicit action, never silent) to re-process them.
        if !quitSavedToFinalize.isEmpty {
            QuitFinalizeRecovery.shared.offer(quitSavedToFinalize)
        }
    }

    /// Everything one refresh scan produces. Assembled OFF the main
    /// actor by `scanRoots` — plain value type, all Sendable.
    nonisolated struct ScanResult: Sendable {
        var loaded: [StoredSession] = []
        var interrupted: [URL] = []
        var quitSaved: [URL] = []
    }

    /// The disk-heavy half of `performRefresh`, factored out so it can
    /// run detached: enumerate the session roots and classify every
    /// directory. Pure with respect to store state — everything it
    /// needs comes in as parameters, everything it learns goes out in
    /// the `ScanResult`.
    nonisolated static func scanRoots(
        _ roots: [URL],
        activeRecordingDirName: String?
    ) -> ScanResult {
        let scanLog = Logger(subsystem: "app.essazanov.Daisy", category: "SessionStore.scan")
        var result = ScanResult()
        for root in roots {
            let entries: [URL]
            do {
                entries = try FileManager.default.contentsOfDirectory(
                    at: root,
                    includingPropertiesForKeys: [.isDirectoryKey, .contentModificationDateKey],
                    options: [.skipsHiddenFiles, .skipsSubdirectoryDescendants]
                )
            } catch {
                scanLog.error("Could not list \(root.path, privacy: .private): \(error.localizedDescription, privacy: .public)")
                continue
            }
            for url in entries {
                let isDir = (try? url.resourceValues(forKeys: [.isDirectoryKey]))?.isDirectory ?? false
                guard isDir else { continue }
                switch Self.classify(directory: url) {
                case .valid(let session):
                    result.loaded.append(session)
                    // A .valid session still carrying the live-recording
                    // marker was saved by Quit/shutdown DURING recording:
                    // stop() flushed the live transcript, but the detached
                    // finalize (full-archive pass + summary) died with the
                    // process. Offer to finish the job — see
                    // QuitFinalizeRecovery. (Finalize Stage 3b removes the
                    // marker on a clean run, so its presence is the tell.)
                    if activeRecordingDirName != url.lastPathComponent,
                       FileManager.default.fileExists(
                           atPath: url.appendingPathComponent(Self.recordingMarkerName).path
                       ) {
                        result.quitSaved.append(url)
                    }
                case .unreadable:
                    break
                case .interrupted(let session):
                    // Interrupted sessions are still real user folders.
                    // Keep them visible while best-effort recovery runs.
                    result.loaded.append(session)
                    // Crash / power-loss leftover with real audio. NEVER
                    // delete. Skip the live recording (still being written);
                    // queue the rest for best-effort recovery.
                    if activeRecordingDirName != url.lastPathComponent {
                        result.interrupted.append(url)
                    }
                }
            }
        }
        return result
    }

    /// Result of classifying a directory inside `Sessions/`. Every
    /// readable folder becomes a visible session, including empty and
    /// audio-only folders. Unreadable folders are never modified.
    /// Name of the marker file `RecordingSession` writes into a session
    /// folder while capture is live (and removes on a clean Stop). Its
    /// presence on a folder with audio but no finished transcript means
    /// "interrupted recording — recover, never delete".
    nonisolated static let recordingMarkerName = ".recording"

    /// A marker-less `.caf` must reach this size before Daisy assumes an
    /// interrupted recording and starts automatic recovery. Smaller
    /// audio-only folders still remain visible in the Library.
    nonisolated static let minRecoverableAudioBytes: Int64 = 256 * 1024

    nonisolated enum ParseResult {
        case valid(StoredSession)
        case unreadable
        /// Audio on disk but no finished transcript — an interrupted
        /// recording (crash / power-loss). NEVER deleted; handed to
        /// `InterruptedRecordingRecovery`.
        case interrupted(StoredSession)
    }

    nonisolated static func classify(directory: URL) -> ParseResult {
        let fm = FileManager.default
        let transcriptURL = directory.appendingPathComponent("transcript.md")

        let retainedAudio = SessionAudioFiles.discover(in: directory)
        let hasMic    = !retainedAudio.microphone.isEmpty
        let hasSystem = !retainedAudio.system.isEmpty
        let hasTranscript = fm.fileExists(atPath: transcriptURL.path)

        // Examine transcript.md once up-front to distinguish a completed
        // recording from one that can be recovered from its audio.
        //
        // iCloud eviction guard (2026-08-20 field audit): a session folder
        // on Desktop/Documents with "Optimize Mac Storage" can have its
        // files evicted — they stay listed under their real names
        // (`fileExists` == true, stat size real) but reading them triggers
        // a synchronous download that FAILS on a full disk. An evicted or
        // unreadable transcript must NEVER look like "no transcript":
        // that's how ≤1.0.7.59 husk-deleted the only copy of a recording
        // (tombstone then synced to iCloud). Don't even attempt the read
        // when the file is evicted — a Library scan must not trigger a
        // download storm over hundreds of sessions.
        let transcriptEvicted = hasTranscript && isCloudEvicted(transcriptURL)
        var transcriptUnreadable = false
        var transcriptBodyEmpty = true
        var hasMeaningfulFrontmatter = false
        if hasTranscript, !transcriptEvicted {
            do {
                let text = try String(contentsOf: transcriptURL, encoding: .utf8)
                let parsed = parseFrontmatter(in: text)
                transcriptBodyEmpty = parsed.body
                    .trimmingCharacters(in: .whitespacesAndNewlines)
                    .isEmpty
                // `title` and `started` are the two fields stop() writes
                // on a successful finish. If either is present we treat
                // the transcript as "real" even if the body is empty
                // (e.g. zero-segment recording that nonetheless completed
                // its lifecycle and deserves a History entry).
                hasMeaningfulFrontmatter = parsed.title != nil || parsed.started != nil
            } catch {
                // Read error ≠ empty file. Treat as "transcript present
                // but unknown" — visible, never recovered, never deleted.
                transcriptUnreadable = true
            }
        }

        // Interrupted recording (crash / power-loss): real audio on disk
        // but no FINISHED transcript. Recoverable — never delete. Identified
        // by the in-progress marker, or (belt-and-suspenders for recordings
        // predating the marker) by a non-trivial .caf on disk. Takes
        // precedence over the normal visible-folder result below.
        let hasFinishedTranscript = hasTranscript
            && (!transcriptBodyEmpty || hasMeaningfulFrontmatter)
        let hasMarker = fm.fileExists(
            atPath: directory.appendingPathComponent(recordingMarkerName).path
        )
        guard let session = parseSession(at: directory) else {
            return .unreadable
        }
        // Never hand an evicted/unreadable folder to recovery: the
        // transcript may be perfectly fine in iCloud, and recovery's full
        // re-transcribe would materialize a multi-GB .caf onto what is
        // likely an already-full disk.
        let audioEvicted = retainedAudio.all.contains(where: isCloudEvicted)
        if (hasMic || hasSystem), !hasFinishedTranscript,
           !transcriptEvicted, !transcriptUnreadable, !audioEvicted,
           hasMarker || largestAudioBytes(retainedAudio.all) >= minRecoverableAudioBytes {
            return .interrupted(session)
        }
        return .valid(session)
    }

    /// True when `url` is an iCloud (FileProvider) item whose bytes are
    /// NOT local — the file is listed under its real name, but any read
    /// triggers a synchronous download that can fail (offline / full
    /// disk). Non-iCloud files always return false.
    nonisolated static func isCloudEvicted(_ url: URL) -> Bool {
        guard let values = try? url.resourceValues(forKeys: [
            .isUbiquitousItemKey, .ubiquitousItemDownloadingStatusKey
        ]) else { return false }
        guard values.isUbiquitousItem == true,
              let status = values.ubiquitousItemDownloadingStatus else { return false }
        return status == .notDownloaded
    }

    /// Largest retained `.caf` part in bytes (0 if none is readable). The
    /// size-based fallback for spotting a recoverable interrupted recording
    /// when the marker is absent.
    nonisolated static func largestAudioBytes(_ urls: [URL]) -> Int64 {
        func size(_ url: URL) -> Int64 {
            guard let attrs = try? FileManager.default.attributesOfItem(atPath: url.path),
                  let n = attrs[.size] as? Int64 else { return 0 }
            return n
        }
        return urls.map(size).max() ?? 0
    }

    /// Permanently delete a session's folder + its contents.
    func delete(_ session: StoredSession) async {
        do {
            try FileManager.default.removeItem(at: session.directoryURL)
            await refresh()
        } catch {
            log.error("Delete failed: \(error.localizedDescription, privacy: .public)")
            lastError = error.localizedDescription
        }
    }

    /// Bulk delete — used by the History view's multi-select shortcut.
    /// One refresh at the end instead of N to avoid UI thrash.
    /// Per-session errors are logged but don't stop the loop.
    func deleteMany(_ sessions: [StoredSession]) async {
        var firstError: String?
        for session in sessions {
            do {
                try FileManager.default.removeItem(at: session.directoryURL)
            } catch {
                log.error("Delete failed for \(session.title, privacy: .private): \(error.localizedDescription, privacy: .public)")
                if firstError == nil {
                    firstError = error.localizedDescription
                }
            }
        }
        await refresh()
        if let firstError {
            lastError = firstError
        }
    }

    /// How many sessions a bulk-delete would actually remove for a
    /// given scope. Mirrors the filtering in `deleteAllSessions` /
    /// `deleteSessions(inFolder:)` exactly — including skipping the
    /// in-progress recording — so a "Delete N recordings?" confirm
    /// shows the true post-delete count rather than a raw
    /// `sessions.count` that might include the live one. Pass `nil`
    /// for the "all recordings" scope, or a folder slug to scope to
    /// one folder.
    func deletableSessionCount(inFolder slug: String? = nil) -> Int {
        sessionsToDelete(inFolder: slug).count
    }

    /// The concrete sessions a bulk-delete would remove for `slug`
    /// (`nil` == every folder). Always excludes the currently-recording
    /// session: its directory has audio but no `transcript.md` mid-
    /// session, and removing it would orphan the open `.caf`
    /// descriptors and break the post-stop transcript write.
    /// A `StoredSession.id` IS its directory name, so the guard is a
    /// direct id comparison. Live folders are intentionally visible now,
    /// so this guard is required for every bulk-delete path.
    private func sessionsToDelete(inFolder slug: String?) -> [StoredSession] {
        var pool = sessions
        if let slug, !slug.isEmpty {
            pool = pool.filter { $0.folderSlug == slug }
        }
        if let active = activeRecordingDirName {
            pool = pool.filter { $0.id != active }
        }
        return pool
    }

    /// Delete EVERY stored session from disk + the in-memory list,
    /// skipping the in-progress recording if one is active. Reuses the
    /// per-session removal path (`deleteMany`) so the FileManager logic,
    /// per-session error capture, and single trailing `refresh()` all
    /// match the multi-select delete. No-op (still refreshes) when
    /// there's nothing to remove.
    func deleteAllSessions() async {
        await deleteMany(sessionsToDelete(inFolder: nil))
    }

    /// Delete every session belonging to `slug` (the `daisy_folder`
    /// frontmatter value, e.g. "inbox" / "work"). Same scoping the
    /// Library sidebar and MCP use (`folderSlug == slug`), same
    /// active-recording skip, and the same `deleteMany` removal path.
    func deleteSessions(inFolder slug: String) async {
        await deleteMany(sessionsToDelete(inFolder: slug))
    }

    /// Persist a speaker-to-attendee mapping for a session. Rewrites
    /// the `daisy_speaker_map:` frontmatter line as a YAML inline
    /// dict (`{A: "Alex", B: "Maria"}`) and refreshes the store so
    /// the Detail view re-renders with the new names.
    func updateSpeakerMap(_ map: [String: String], for session: StoredSession) async {
        guard let url = session.transcriptURL else { return }
        do {
            var text = try String(contentsOf: url, encoding: .utf8)
            let encoded = Self.encodeYAMLDict(map)
            text = Self.upsertFrontmatter(in: text, key: "daisy_speaker_map", value: encoded)
            try text.write(to: url, atomically: true, encoding: .utf8)
            await refresh()
        } catch {
            log.error("Speaker map save failed: \(error.localizedDescription, privacy: .public)")
            lastError = error.localizedDescription
        }
    }

    nonisolated static func encodeYAMLDict(_ map: [String: String]) -> String {
        if map.isEmpty { return "{}" }
        let pairs = map.keys.sorted().map { k in
            let v = map[k] ?? ""
            return "\(k): \"\(v.replacingOccurrences(of: "\"", with: "\\\""))\""
        }
        return "{\(pairs.joined(separator: ", "))}"
    }

    /// Move a session to a folder. Rewrites the `daisy_folder:` line
    /// in the transcript markdown frontmatter (adding it if missing)
    /// and reloads the store so chips / lists update.
    func moveSession(_ session: StoredSession, to folder: SessionFolder) async {
        await moveMany([session], to: folder)
    }

    /// Move several recordings or notes with one trailing refresh. The
    /// single-item path delegates here as well so both operations preserve
    /// legacy note kinds and report partial failures identically.
    func moveMany(_ sessions: [StoredSession], to folder: SessionFolder) async {
        var firstError: String?
        for session in sessions {
            guard let url = session.transcriptURL else { continue }
            do {
                var text = try String(contentsOf: url, encoding: .utf8)
                text = Self.upsertFrontmatter(in: text, key: "daisy_folder", value: folder.slug)
                // Pin the kind on every move. Otherwise a LEGACY note (no
                // `daisy_kind:` on disk, currently inferred `.note` only
                // because it sits in the Notes folder) that the user moves
                // to another project would, on the next scan, infer as a
                // `.recording` and vanish from the Notes tab.
                text = Self.upsertFrontmatter(in: text, key: "daisy_kind", value: session.kind.rawValue)
                try text.write(to: url, atomically: true, encoding: .utf8)
            } catch {
                log.error("Move failed for \(session.title, privacy: .private): \(error.localizedDescription, privacy: .public)")
                if firstError == nil {
                    firstError = error.localizedDescription
                }
            }
        }
        await refresh()
        if let firstError {
            lastError = firstError
        }
    }

    /// Distinct, non-empty tags currently in use across the store —
    /// sorted by frequency desc then alphabetically. Powers the
    /// autocomplete dropdown in SessionDetail's tag editor so the
    /// user can pick "Mediacube" once instead of typing it ten
    /// times (and risking spelling drift between sessions).
    var distinctTagsByFrequency: [String] {
        var counts: [String: Int] = [:]
        for s in sessions {
            let t = s.tag.trimmingCharacters(in: .whitespaces)
            guard !t.isEmpty else { continue }
            counts[t, default: 0] += 1
        }
        return counts
            .sorted { lhs, rhs in
                if lhs.value != rhs.value { return lhs.value > rhs.value }
                return lhs.key.lowercased() < rhs.key.lowercased()
            }
            .map(\.key)
    }

    /// Rewrite the session's `title:` frontmatter line and reload the
    /// store so History rows / the Detail header re-render. Mirrors
    /// `setTag` exactly (same `upsertFrontmatter` + YAML-quote round
    /// trip the `title` reader in `parseFrontmatter` already strips).
    /// No dedicated UI button today — title is otherwise only set at
    /// record time — but it's the same on-disk field, so editing it
    /// here is the canonical, fully-reversible mutation. Empty/blank
    /// titles are rejected by the caller (an empty `title:` would make
    /// `parseSession` fall back to the folder-name id, which is
    /// confusing) — this method trusts its input is non-empty.
    func setTitle(_ title: String, for session: StoredSession) async {
        let trimmed = title.trimmingCharacters(in: .whitespacesAndNewlines)
        // No transcript — nothing to carry a `title:` frontmatter line.
        // The visible name of such a session IS its directory name
        // (Finder-created / empty / audio-only folders), so a rename
        // means renaming the folder itself.
        guard let url = session.transcriptURL else {
            await renameDirectory(session, to: trimmed)
            return
        }
        do {
            var text = try String(contentsOf: url, encoding: .utf8)
            // Same quoting as MarkdownExporter.yamlQuote (escape `\`
            // then `"`), so a title with quotes/colons survives the
            // YAML round-trip the same way the record-time writer
            // produces it.
            let escaped = trimmed
                .replacingOccurrences(of: "\\", with: "\\\\")
                .replacingOccurrences(of: "\"", with: "\\\"")
            let yamlValue = "\"\(escaped)\""
            text = Self.upsertFrontmatter(in: text, key: "title", value: yamlValue)
            try text.write(to: url, atomically: true, encoding: .utf8)
            await refresh()
        } catch {
            log.error("Set title failed: \(error.localizedDescription, privacy: .public)")
            lastError = error.localizedDescription
        }
    }

    /// Rename a transcript-less session by renaming its directory. The
    /// directory name IS the session id, so the row re-appears under the
    /// new id after refresh. Guards: never the live recording (open .caf
    /// descriptors), never onto an existing folder, and the new name is
    /// sanitized for the filesystem.
    private func renameDirectory(_ session: StoredSession, to rawName: String) async {
        guard session.id != activeRecordingDirName else { return }
        var name = rawName
            .replacingOccurrences(of: "/", with: "-")
            .replacingOccurrences(of: ":", with: "-")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        while name.hasPrefix(".") { name.removeFirst() }
        guard !name.isEmpty, name != session.id else { return }

        let parent = session.directoryURL.deletingLastPathComponent()
        let destination = parent.appendingPathComponent(name, isDirectory: true)
        guard !FileManager.default.fileExists(atPath: destination.path) else {
            lastError = String(localized: "A folder with this name already exists.")
            return
        }
        let ticket = SessionsFolder.acquireAccess(to: session.directoryURL)
        defer { ticket?.release() }
        do {
            try FileManager.default.moveItem(at: session.directoryURL, to: destination)
            await refresh()
        } catch {
            log.error("Folder rename failed: \(error.localizedDescription, privacy: .public)")
            lastError = error.localizedDescription
        }
    }

    /// Update the `daisy_tag:` value on a session and reload the
    /// store so the History sidebar selector refreshes. Pass an
    /// empty string to remove the tag (the line itself stays as
    /// `daisy_tag: ""` — harmless, reads back as untagged).
    func setTag(_ tag: String, for session: StoredSession) async {
        guard let url = session.transcriptURL else { return }
        let trimmed = tag.trimmingCharacters(in: .whitespaces)
        do {
            var text = try String(contentsOf: url, encoding: .utf8)
            // Quote the value so spaces / special chars survive the
            // YAML round-trip parsing (`Acme Inc` etc.).
            let yamlValue = "\"\(trimmed.replacingOccurrences(of: "\"", with: "\\\""))\""
            text = Self.upsertFrontmatter(in: text, key: "daisy_tag", value: yamlValue)
            try text.write(to: url, atomically: true, encoding: .utf8)
            await refresh()
        } catch {
            log.error("Set tag failed: \(error.localizedDescription, privacy: .public)")
            lastError = error.localizedDescription
        }
    }

    /// Mutate (or insert) one `key: value` line inside the YAML
    /// frontmatter at the top of `text`. If there's no frontmatter
    /// at all, a fresh `---` block is prepended.
    nonisolated static func upsertFrontmatter(in text: String, key: String, value: String) -> String {
        let lines = text.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)
        if lines.first?.trimmingCharacters(in: .whitespaces) != "---" {
            return "---\n\(key): \(value)\n---\n\n\(text)"
        }
        var closeIdx: Int?
        for i in 1..<lines.count {
            if lines[i].trimmingCharacters(in: .whitespaces) == "---" {
                closeIdx = i
                break
            }
        }
        guard let endIdx = closeIdx else {
            return "---\n\(key): \(value)\n---\n\n\(text)"
        }
        var copy = lines
        let newLine = "\(key): \(value)"
        if let existing = (1..<endIdx).first(where: { copy[$0].hasPrefix("\(key):") }) {
            copy[existing] = newLine
        } else {
            copy.insert(newLine, at: endIdx)
        }
        return copy.joined(separator: "\n")
    }

    /// Replace a session's `summary.json` and reload metadata.
    @discardableResult
    func updateSummary(_ summary: MeetingSummary, for session: StoredSession) async -> Bool {
        let url = session.directoryURL.appendingPathComponent("summary.json")
        do {
            let data = try JSONEncoder().encode(summary)
            try data.write(to: url, options: .atomic)
            await refresh()
            return true
        } catch {
            log.error("Save summary failed: \(error.localizedDescription, privacy: .public)")
            lastError = error.localizedDescription
            return false
        }
    }

    /// Mark a session as currently summarizing. Called by
    /// `RecordingSession.stop()` right before it spins up the
    /// detached summary task, so SessionDetailView can render the
    /// skeleton state for that session even before the History list
    /// has been re-scanned. Pair with `finishGenerating(id:)`.
    func beginGenerating(_ sessionID: String) {
        guard !sessionID.isEmpty else { return }
        sessionsGenerating.insert(sessionID)
    }

    /// Mark a session's summary as done and reload its on-disk
    /// metadata. Called from inside the detached summary task once
    /// `summary.json` (and any auto-send byproducts) have flushed.
    /// Performs a targeted reload of just that one folder rather than
    /// a full `refresh()` — cheaper, and avoids touching unrelated
    /// rows while the user is browsing History.
    ///
    /// If the session isn't already in `sessions` (e.g. user is on
    /// the first launch with no prior data) this still calls
    /// `refresh()` so the new row appears.
    func finishGenerating(_ sessionID: String) async {
        sessionsGenerating.remove(sessionID)
        await reloadSession(id: sessionID)
    }

    /// Re-parse one session folder and replace the matching row in
    /// `sessions` in-place. Used by `finishGenerating` so the UI
    /// reactively picks up the freshly-written `summary.json`
    /// without re-scanning every session on disk.
    func reloadSession(id: String) async {
        guard let existing = sessions.first(where: { $0.id == id }) else {
            // Not in our list yet — full refresh will find it.
            await refresh()
            return
        }
        // parseSession needs filesystem access; security-scoped folder
        // may need a fresh ticket. Cheap path first — if the directory
        // is inside the app container, no scope needed. If it's in the
        // user-picked folder, acquire the scope just for this read.
        let containerOK = (try? Self.defaultSessionsDirectory())?
            .resolvingSymlinksInPath()
            .path
        let isInContainer = existing.directoryURL
            .resolvingSymlinksInPath()
            .deletingLastPathComponent()
            .path == containerOK
        var ticket: SessionsFolder.AccessTicket?
        if !isInContainer {
            let bases = ([SessionsFolder.resolveUserFolder()].compactMap { $0 }
                + SessionsFolder.resolveLegacyFolders())
            if let owningBase = bases.first(where: {
                existing.directoryURL.standardizedFileURL.path
                    .hasPrefix(SessionsFolder.sessionsDirectory(in: $0).standardizedFileURL.path + "/")
            }) {
                ticket = SessionsFolder.acquireAccess(to: owningBase)
            }
        }
        defer { ticket?.release() }

        guard let updated = Self.parseSession(at: existing.directoryURL) else {
            log.warning("reloadSession(\(id, privacy: .public)) failed to parse")
            return
        }
        if let idx = sessions.firstIndex(where: { $0.id == id }) {
            sessions[idx] = updated
            // Targeted index invalidation: drop the cached token set so
            // the next search re-tokenizes this session even if the
            // content stamp were unchanged.
            searchTokenCache.removeValue(forKey: id)
            searchIndexDirty = true
        }
    }

    // MARK: - Search

    /// Substring search over `pool`, accelerated by an inverted token
    /// index. The result is IDENTICAL to
    /// `pool.filter { $0.matches(query: query) }` — the index is only a
    /// candidate prefilter, computed so that it can never drop a true
    /// substring match; the final check is still the existing
    /// `StoredSession.matches` scan, run on the (few) candidates.
    /// Queries with no alphanumeric tokens (pure punctuation/symbols)
    /// fall back to the full scan. Used by LibraryView's search field
    /// and the MCP `search_sessions` tool.
    func sessionsMatching(_ query: String, in pool: [StoredSession]) -> [StoredSession] {
        let trimmed = query.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return pool }
        let t0 = DispatchTime.now().uptimeNanoseconds
        let queryTokens = Self.searchTokens(in: trimmed)
        var candidates = pool
        var usedIndex = false
        if !queryTokens.isEmpty {
            reconcileSearchIndex()
            let ids = candidateSessionIDs(forQueryTokens: queryTokens)
            candidates = pool.filter { ids.contains($0.id) }
            usedIndex = true
        }
        let results = candidates.filter { $0.matches(query: trimmed) }
        let ms = Double(DispatchTime.now().uptimeNanoseconds - t0) / 1_000_000
        // Privacy-safe: counts and timing only, never the query text.
        log.debug("Search: \(ms, format: .fixed(precision: 2), privacy: .public) ms, pool \(pool.count, privacy: .public), candidates \(candidates.count, privacy: .public), results \(results.count, privacy: .public), index \(usedIndex ? "on" : "off", privacy: .public)")
        return results
    }

    /// Bring the inverted index in line with `sessions`. Lazy — runs
    /// only when a search happens after the store changed. Sessions
    /// whose content stamp matches the cache keep their token set;
    /// changed/new sessions are re-tokenized; postings of deleted
    /// sessions are pruned.
    private func reconcileSearchIndex() {
        guard searchIndexDirty else { return }
        let t0 = DispatchTime.now().uptimeNanoseconds
        var liveIDs = Set<String>()
        liveIDs.reserveCapacity(sessions.count)
        var retokenized = 0
        for session in sessions {
            liveIDs.insert(session.id)
            let stamp = Self.searchStamp(of: session)
            if let cached = searchTokenCache[session.id], cached.stamp == stamp {
                continue
            }
            var newTokens = Set<String>()
            for field in Self.searchableFields(of: session) {
                newTokens.formUnion(Self.searchTokens(in: field))
            }
            if let old = searchTokenCache[session.id] {
                for token in old.tokens.subtracting(newTokens) {
                    searchTokenIndex[token]?.remove(session.id)
                    if searchTokenIndex[token]?.isEmpty == true {
                        searchTokenIndex.removeValue(forKey: token)
                    }
                }
                for token in newTokens.subtracting(old.tokens) {
                    searchTokenIndex[token, default: []].insert(session.id)
                }
            } else {
                for token in newTokens {
                    searchTokenIndex[token, default: []].insert(session.id)
                }
            }
            searchTokenCache[session.id] = (stamp, newTokens)
            retokenized += 1
        }
        // Prune postings for sessions that no longer exist.
        for id in Set(searchTokenCache.keys).subtracting(liveIDs) {
            guard let old = searchTokenCache.removeValue(forKey: id) else { continue }
            for token in old.tokens {
                searchTokenIndex[token]?.remove(id)
                if searchTokenIndex[token]?.isEmpty == true {
                    searchTokenIndex.removeValue(forKey: token)
                }
            }
        }
        searchIndexDirty = false
        let ms = Double(DispatchTime.now().uptimeNanoseconds - t0) / 1_000_000
        log.debug("Search index reconcile: \(ms, format: .fixed(precision: 2), privacy: .public) ms, retokenized \(retokenized, privacy: .public)/\(self.sessions.count, privacy: .public) sessions, \(self.searchTokenIndex.count, privacy: .public) distinct tokens")
    }

    /// Candidate session IDs for a tokenized query — guaranteed to be a
    /// SUPERSET of the sessions whose searchable text contains the raw
    /// query as a substring (no false negatives):
    ///  • single-token query: the match may sit mid-word ("cube" in
    ///    "Mediacube"), so accept any indexed token CONTAINING it;
    ///  • multi-token query: the first query token must END a document
    ///    token, interior tokens must match exactly, and the last must
    ///    START a document token ("llo wor" still finds "hello world").
    /// The vocabulary scan for prefix/suffix/infix is tiny compared to
    /// scanning the full transcript corpus.
    private func candidateSessionIDs(forQueryTokens queryTokens: [String]) -> Set<String> {
        func ids(matching predicate: (String) -> Bool) -> Set<String> {
            var out = Set<String>()
            for (token, sessionIDs) in searchTokenIndex where predicate(token) {
                out.formUnion(sessionIDs)
            }
            return out
        }
        guard let first = queryTokens.first else { return [] }
        if queryTokens.count == 1 {
            return ids { $0.contains(first) }
        }
        var result = ids { $0.hasSuffix(first) }
        for token in queryTokens.dropFirst().dropLast() {
            if result.isEmpty { return result }
            result.formIntersection(searchTokenIndex[token] ?? [])
        }
        if result.isEmpty { return result }
        let last = queryTokens[queryTokens.count - 1]
        result.formIntersection(ids { $0.hasPrefix(last) })
        return result
    }

    /// Unicode-aware tokenizer: lowercases, then splits into maximal
    /// runs of alphanumerics (letters incl. Cyrillic, digits, combining
    /// marks). Order-preserving; duplicates kept (callers Set-ify when
    /// needed). Matches the lowercasing `StoredSession.matches` uses.
    /// Internal (not `private`) so the DaisyTests smoke suite can lock
    /// tokenizer behaviour — the inverted search index is only correct
    /// if this splits exactly like `StoredSession.matches` lowercases.
    nonisolated static func searchTokens(in text: String) -> [String] {
        let alphanumerics = CharacterSet.alphanumerics
        var tokens: [String] = []
        var current = ""
        for scalar in text.lowercased().unicodeScalars {
            if alphanumerics.contains(scalar) {
                current.unicodeScalars.append(scalar)
            } else if !current.isEmpty {
                tokens.append(current)
                current = ""
            }
        }
        if !current.isEmpty {
            tokens.append(current)
        }
        return tokens
    }

    /// The exact fields `StoredSession.matches(query:)` scans. The
    /// index MUST be built from the same text, or the prefilter could
    /// drop true matches. Keep the two in sync.
    nonisolated private static func searchableFields(of session: StoredSession) -> [String] {
        var fields = [session.title, session.tag, session.transcriptText]
        if let s = session.summary {
            fields.append(s.summary)
            fields.append(contentsOf: s.actionItems)
            fields.append(s.clientFollowUp)
        }
        return fields
    }

    /// Cheap change stamp for a session's searchable content. Short
    /// fields (title/tag/summary) are hashed in full; the transcript
    /// body only by UTF-8 byte length — O(1) for native strings. The
    /// body is written exactly once at Stop and no code path edits it
    /// in place (all editors touch frontmatter or summary.json), so
    /// length is a sufficient change detector and we avoid re-hashing
    /// megabytes of text after every refresh(). `reloadSession` also
    /// drops the cache entry outright as a belt-and-suspenders.
    nonisolated private static func searchStamp(of session: StoredSession) -> Int {
        var hasher = Hasher()
        hasher.combine(session.title)
        hasher.combine(session.tag)
        // Hash the CONTENT, not just its length — an external edit of
        // the same byte count (Obsidian find-replace, fixing a name)
        // previously kept the stale token set forever. The text is
        // already in memory; hashing it is far cheaper than the
        // tokenization this stamp exists to skip.
        hasher.combine(session.transcriptText)
        if let s = session.summary {
            hasher.combine(s.summary)
            for item in s.actionItems { hasher.combine(item) }
            hasher.combine(s.clientFollowUp)
        }
        return hasher.finalize()
    }

    // MARK: - Filesystem helpers

    /// Sessions directory inside the app's container. Always
    /// readable, used as the fallback when no user-picked folder
    /// is set AND also scanned alongside the user folder so old
    /// sessions remain visible after the user reroutes.
    static func defaultSessionsDirectory() throws -> URL {
        let base = try FileManager.default.url(
            for: .applicationSupportDirectory,
            in: .userDomainMask,
            appropriateFor: nil,
            create: true
        )
        let dir = base.appendingPathComponent("Daisy/Sessions", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    nonisolated static func parseSession(at directory: URL) -> StoredSession? {
        let fm = FileManager.default
        let id = directory.lastPathComponent

        let transcriptURL = directory.appendingPathComponent("transcript.md")
        let summaryURL = directory.appendingPathComponent("summary.json")
        let screenshotsDir = directory.appendingPathComponent("screenshots", isDirectory: true)
        let retainedAudio = SessionAudioFiles.discover(in: directory)

        // Read transcript.md (lazily — only frontmatter + body for search).
        var title = id
        // Empty and hand-created folders have no frontmatter date. Use
        // filesystem metadata rather than Date() so rows do not jump to
        // "now" and reorder on every Library refresh.
        let directoryDates = try? directory.resourceValues(
            forKeys: [.creationDateKey, .contentModificationDateKey]
        )
        var startedAt = Self.dateFromFolderName(id)
            ?? directoryDates?.creationDate
            ?? directoryDates?.contentModificationDate
            ?? .distantPast
        var durationSec = 0
        var locale = "auto"
        var transcriptBody = ""
        var transcriptPreview = ""
        // Evicted-by-iCloud files must not be read during a scan — each
        // read triggers a synchronous download (see isCloudEvicted).
        let transcriptEvicted = fm.fileExists(atPath: transcriptURL.path)
            && Self.isCloudEvicted(transcriptURL)
        if !transcriptEvicted,
           let text = try? String(contentsOf: transcriptURL, encoding: .utf8) {
            let parsed = parseFrontmatter(in: text)
            title = parsed.title ?? title
            if let dateStr = parsed.started,
               let parsedDate = Self.iso.date(from: dateStr) {
                startedAt = parsedDate
            }
            durationSec = parsed.durationSec ?? 0
            locale = parsed.locale ?? locale
            transcriptBody = parsed.body
            transcriptPreview = Self.preview(from: parsed.body)
        }

        // Load summary if present.
        var summary: MeetingSummary?
        if let data = try? Data(contentsOf: summaryURL) {
            summary = try? JSONDecoder().decode(MeetingSummary.self, from: data)
        }

        // Screenshot files, in capture order (by frame number — see
        // ScreenshotFile.ordered).
        var screenshots: [URL] = []
        if let entries = try? fm.contentsOfDirectory(at: screenshotsDir, includingPropertiesForKeys: nil) {
            screenshots = ScreenshotFile.ordered(entries)
        }
        // Empty for anything recorded before the index existed — the UI
        // then shows frames without times rather than guessing.
        let screenshotOffsets = ScreenshotIndex.load(from: screenshotsDir)
        // Empty when OCR found nothing legible — callers fall back to
        // every frame rather than hiding the affordance.
        let screenshotHighlights = ScreenshotIndex.loadHighlights(from: screenshotsDir)

        // Folder slug + tag + speaker mapping + system-audio status
        // — parsed once at load. NB: `parsedFm` here is the
        // ParsedFrontmatter struct, distinct from the outer-scope
        // `fm` (FileManager) — don't conflate the two.
        var folderSlug = "inbox"
        var kind: SessionKind = .recording
        var tag = ""
        var attendees: [String] = []
        var attendeeEmails: [String] = []
        var linkedEventTitle: String?
        var speakerMap: [String: String] = [:]
        var systemAudioStatus: String?
        var micOnlyCause: String?
        if !transcriptEvicted,
           let text = try? String(contentsOf: transcriptURL, encoding: .utf8) {
            let parsedFm = parseFrontmatter(in: text)
            folderSlug = parsedFm.folder ?? "inbox"
            // Explicit `daisy_kind:` wins; otherwise INFER for legacy
            // files. Historically the ONLY way to make a note was to put
            // it in the Notes folder (voice notes + side notes both wrote
            // `daisy_folder: notes`), so a Notes-folder session with no
            // `daisy_kind:` is a note and everything else is a recording.
            // This keeps every pre-split file classified correctly with
            // zero on-disk rewrite. Once such a note is moved to another
            // folder, `moveSession` stamps `daisy_kind:` so the inference
            // can't later flip it to a recording.
            if let raw = parsedFm.kind, let explicit = SessionKind(rawValue: raw) {
                kind = explicit
            } else {
                kind = (folderSlug == SessionFolder.notes.slug) ? .note : .recording
            }
            tag = parsedFm.tag ?? ""
            attendees = parsedFm.attendees
            attendeeEmails = parsedFm.attendeeEmails
            linkedEventTitle = parsedFm.linkedEventTitle
            speakerMap = parsedFm.speakerMap
            systemAudioStatus = parsedFm.systemAudioStatus
            micOnlyCause = parsedFm.micOnlyCause
        }

        // speakers.json sidecar — just the centroid KEY set, not the
        // 256-dim embeddings (those are heavy and the UI only needs to
        // know "does this transcript ID have a saved voice fingerprint
        // or not"). 1.0.7.1 addition for the speaker-mapping UX.
        var centroidIDs: Set<String> = []
        let speakersURL = directory.appendingPathComponent("speakers.json")
        if let data = try? Data(contentsOf: speakersURL),
           let parsed = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
           let centroids = parsed["centroids"] as? [String: Any] {
            centroidIDs = Set(centroids.keys)
        }

        let meetingPreparation = MeetingPreparationSnapshot.load(from: directory)
        let planAnalysis = MeetingPlanAnalysis.load(from: directory)
        let planAnalysisError = MeetingPlanAnalysisErrorRecord.load(from: directory)

        return StoredSession(
            id: id,
            directoryURL: directory,
            title: title,
            startedAt: startedAt,
            durationSec: durationSec,
            locale: locale,
            transcriptPreview: transcriptPreview,
            transcriptText: transcriptBody,
            hasMicAudio: !retainedAudio.microphone.isEmpty,
            hasSystemAudio: !retainedAudio.system.isEmpty,
            screenshotURLs: screenshots,
            screenshotOffsets: screenshotOffsets,
            screenshotHighlights: screenshotHighlights,
            summary: summary,
            transcriptURL: fm.fileExists(atPath: transcriptURL.path) ? transcriptURL : nil,
            folderSlug: folderSlug,
            kind: kind,
            tag: tag,
            meetingAttendees: attendees,
            meetingAttendeeEmails: attendeeEmails,
            linkedEventTitle: linkedEventTitle,
            meetingPreparation: meetingPreparation,
            planAnalysis: planAnalysis,
            planAnalysisError: planAnalysisError,
            speakerMap: speakerMap,
            speakerCentroidIDs: centroidIDs,
            systemAudioStatus: systemAudioStatus,
            micOnlyCause: micOnlyCause,
            // "Evicted" only when the PRIMARY content is unreachable: a
            // local transcript with cloud-evicted audio still reads fine —
            // the audio player is the only thing that would trigger a
            // download, and it copes.
            cloudEvicted: transcriptEvicted
                || (!fm.fileExists(atPath: transcriptURL.path)
                    && retainedAudio.all.contains(where: Self.isCloudEvicted))
        )
    }

    nonisolated private static func preview(from body: String) -> String {
        // Skip leading "# Title", quote-style metadata, and section
        // headings. Grab the first chunk of plain prose, trim to 220 chars.
        let lines = body.split(separator: "\n", omittingEmptySubsequences: false)
        var collected: [String] = []
        var charCount = 0
        for raw in lines {
            let line = raw.trimmingCharacters(in: .whitespaces)
            guard !line.isEmpty else { continue }
            if line.hasPrefix("#") || line.hasPrefix(">") || line.hasPrefix("---") {
                continue
            }
            collected.append(line)
            charCount += line.count
            if charCount > 220 { break }
        }
        let joined = collected.joined(separator: " ")
        if joined.count <= 220 { return joined }
        return String(joined.prefix(217)) + "…"
    }

    nonisolated private static func dateFromFolderName(_ name: String) -> Date? {
        // Folder names come from `ISO8601DateFormatter` with the
        // `:` characters in time/offset replaced by `-` for FAT/
        // sandbox safety. Two shapes occur depending on whether the
        // formatter's timeZone was UTC (Z suffix) or local (offset).
        // The current production format is UTC → Z suffix, but older
        // folders may still carry an explicit offset, so we accept
        // both.
        //
        //   2026-05-17T12-37-36Z           (UTC, Z suffix)
        //   2026-05-16T22-30-00+08-00      (explicit offset)
        //
        // Restore colons before handing off to ISO8601DateFormatter.
        let zRegex      = /^(\d{4})-(\d{2})-(\d{2})T(\d{2})-(\d{2})-(\d{2})Z$/
        let offsetRegex = /^(\d{4})-(\d{2})-(\d{2})T(\d{2})-(\d{2})-(\d{2})([+-])(\d{2})-(\d{2})$/

        if let m = name.wholeMatch(of: zRegex) {
            let restored = "\(m.1)-\(m.2)-\(m.3)T\(m.4):\(m.5):\(m.6)Z"
            return iso.date(from: restored)
        }
        if let m = name.wholeMatch(of: offsetRegex) {
            let restored = "\(m.1)-\(m.2)-\(m.3)T\(m.4):\(m.5):\(m.6)\(m.7)\(m.8):\(m.9)"
            return iso.date(from: restored)
        }
        return nil
    }

    // ISO8601DateFormatter is documented as thread-safe but not declared
    // `Sendable` in Foundation, so we have to mark this `unsafe`.
    nonisolated(unsafe) private static let iso: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime]
        return f
    }()
}

// MARK: - Stored session value

/// Whether a stored session is a full RECORDING (meeting / interrupted-
/// recovery) or a NOTE (voice note / side-note excerpt). Replaces the
/// old "a note is anything living in the Notes folder" coupling: notes
/// and recordings now share the same projects/folders AND tags, and are
/// told apart ONLY by this field. Persisted in transcript frontmatter as
/// `daisy_kind: recording|note`; `rawValue` IS the on-disk token, so keep
/// the cases stable. Sessions saved before this field existed carry no
/// `daisy_kind:` — `parseSession` INFERS it (Notes folder ⇒ note, else
/// recording), so every legacy file keeps working with zero rewrite.
nonisolated enum SessionKind: String, Sendable {
    case recording
    case note
}

nonisolated enum SessionContentState: Sendable, Equatable {
    case transcript
    case audioOnly
    case empty
    /// Files exist but their bytes live in iCloud (evicted by "Optimize
    /// Mac Storage"). Content can't be shown until the user downloads
    /// them — e.g. via Finder's cloud icon on the session folder.
    case inCloud
}

struct StoredSession: Identifiable, Sendable {
    let id: String          // = directory name
    let directoryURL: URL
    let title: String
    let startedAt: Date
    let durationSec: Int
    let locale: String
    let transcriptPreview: String
    /// Full transcript body for search. Trimmed of frontmatter.
    let transcriptText: String
    let hasMicAudio: Bool
    let hasSystemAudio: Bool
    let screenshotURLs: [URL]
    /// Screenshot filename → position on the recording's timeline, from
    /// `screenshots/index.json`. Same clock as the transcript's [mm:ss]
    /// markers. Empty for sessions recorded before the index existed;
    /// see `ScreenshotIndex`.
    let screenshotOffsets: [String: Double]
    /// Frames OCR dedup judged to be a new screen, in capture order.
    /// Empty when nothing legible was captured — see
    /// `distinctScreenshots`, which falls back to every frame.
    let screenshotHighlights: [String]
    let summary: MeetingSummary?
    let transcriptURL: URL?
    /// Folder slug, taken from `daisy_folder:` frontmatter. Defaults
    /// to "inbox" for transcripts that predate folder support.
    let folderSlug: String
    /// Recording vs note — from `daisy_kind:` frontmatter, or inferred
    /// for legacy files (see `SessionKind` / `parseSession`). Drives the
    /// Library (`.recording`) vs Notes (`.note`) tab split; INDEPENDENT
    /// of `folderSlug`, so a note or a recording can live in any folder.
    let kind: SessionKind
    /// Free-form tag (`daisy_tag:` in frontmatter; legacy
    /// `daisy_client:` also accepted on read for sessions saved
    /// pre-1.0.5.2). Empty == "untagged" — sidebar selector groups
    /// these together. Set by `TagSuggestion` when binding to a
    /// calendar event with external attendees, or edited manually
    /// from the detail view.
    let tag: String
    /// Attendees captured from the bound EKEvent when this session
    /// was started from the calendar. Empty otherwise.
    let meetingAttendees: [String]
    /// Attendee email addresses from the bound calendar event
    /// (`daisy_event_emails` frontmatter, 1.0.7.10). Lowercased +
    /// deduped at capture time. Empty for manual recordings or events
    /// with no invitee emails. Used by the speaker-match flow to
    /// resolve a calendar attendee to a known `SpeakerProfile` by
    /// email, and by SessionDetailView to attach an email to a profile
    /// when the user names a speaker after the matching attendee.
    let meetingAttendeeEmails: [String]
    /// Title of the calendar event this session was bound to at
    /// start time (e.g. "Customer call · Maria — Acme"). Nil for
    /// manual recordings with no calendar binding. Used by the
    /// SpeakerNameRow attendee picker as a header so the user can
    /// verify the attendee list is from the expected event.
    let linkedEventTitle: String?
    /// Immutable preparation captured when this recording began. Nil for
    /// manual and legacy sessions. Stored in `meeting-preparation.json`.
    let meetingPreparation: MeetingPreparationSnapshot?
    /// Optional second-pass plan analysis. Independent of summary.json.
    let planAnalysis: MeetingPlanAnalysis?
    /// Last analysis failure, if any. A summary can still be fully valid.
    let planAnalysisError: MeetingPlanAnalysisErrorRecord?
    /// User-supplied mapping from speaker id (`"A"`, `"B"`, …) to
    /// real attendee name. Read from `daisy_speaker_map:`
    /// frontmatter. Empty until user fills it in via Detail view.
    let speakerMap: [String: String]
    /// Keys of `centroids` in this session's `speakers.json` sidecar.
    /// Read at session-load time so SessionDetailView can tell which
    /// transcript speaker IDs have a saved voice fingerprint and
    /// which don't (fragmented clusters that ended up in transcript
    /// without a clean centroid). Used by the Name-the-speakers UI
    /// to flag "session only" rows. Empty for sessions that predate
    /// speakers.json (pre-1.0.4) or where diarization didn't run.
    let speakerCentroidIDs: Set<String>
    /// Status of system-audio capture for this session, read from
    /// `daisy_system_audio_status:` frontmatter. Possible values:
    /// `"ok"` (frames received), `"empty"` (capture was on but no
    /// frames arrived — typically Bluetooth output or the macOS
    /// 26.0.x SCStream regression), or `nil` for sessions that
    /// predate this field. SessionDetailView reads it to show the
    /// "couldn't capture the other side" banner so the user
    /// understands why every transcript line collapses to their
    /// own display name instead of per-speaker labels.
    let systemAudioStatus: String?
    /// Raw `MicOnlyCause` value from `daisy_mic_only:` frontmatter —
    /// present only when Daisy KNOWS why the other side is missing
    /// (permission off, or the loopback stream refused to start /
    /// resume). Nil for a healthy meeting, for a dictation or voice
    /// note, and for every session recorded before 1.0.7.64. Distinct
    /// from `systemAudioStatus == "empty"`, which is the symptom and is
    /// also what a Bluetooth output route or a silent meeting looks
    /// like; this one names a cause the user can act on.
    var micOnlyCause: String? = nil
    /// True when transcript.md or a retained .caf is present on disk but
    /// its bytes were evicted to iCloud — reading would require a
    /// download. Sessions built in-memory after a live recording are
    /// never evicted, hence the default.
    var cloudEvicted: Bool = false

    var hasSummary: Bool { summary != nil }
    var hasScreenshots: Bool { !screenshotURLs.isEmpty }

    /// True when this session can navigate between transcript and
    /// screenshots — it has frames AND the timeline index that says when
    /// each was taken. False for anything recorded before the index
    /// existed, where the controls are simply absent.
    var hasScreenTimeline: Bool {
        !screenshotURLs.isEmpty && !screenshotOffsets.isEmpty
    }

    /// The frame that was on screen at `seconds` — the last one captured
    /// at or BEFORE that moment.
    ///
    /// Not "nearest": capture runs on an interval, so an exact match
    /// essentially never happens, and the nearest frame is often the
    /// NEXT one — a slide that was switched to ten seconds after the
    /// line was spoken. What was actually on screen is the previous one.
    /// Falls back to the earliest frame for a moment that predates every
    /// capture.
    func screenshot(at seconds: Double) -> URL? {
        var best: URL?
        var bestOffset = -Double.infinity
        for url in screenshotURLs {
            guard let offset = screenshotOffsets[url.lastPathComponent] else { continue }
            if offset <= seconds, offset > bestOffset {
                bestOffset = offset
                best = url
            }
        }
        return best ?? screenshotURLs.first
    }

    /// Where a frame sits on the timeline, if it's indexed.
    func offset(of screenshot: URL) -> Double? {
        screenshotOffsets[screenshot.lastPathComponent]
    }

    /// The frames worth stepping through: distinct screens when OCR
    /// found any, otherwise every frame.
    ///
    /// Falling back rather than hiding the control is deliberate. Dedup
    /// works on recognised TEXT, so a screen-share with no legible text
    /// — a video, a photo, a grid of faces — yields nothing at all. The
    /// pictures still exist and are still worth walking; a control that
    /// vanishes for those sessions reads as a bug, and a slideshow is a
    /// smaller cost than a missing feature (Egor, 2026-07-29).
    var distinctScreenshots: [URL] {
        guard !screenshotHighlights.isEmpty else { return screenshotURLs }
        let wanted = Set(screenshotHighlights)
        let matched = screenshotURLs.filter { wanted.contains($0.lastPathComponent) }
        return matched.isEmpty ? screenshotURLs : matched
    }

    /// Disk-backed content state used by Library and detail UI. A directory
    /// itself is always a recording entry; this only describes what Daisy
    /// found inside it.
    var contentState: SessionContentState {
        if cloudEvicted { return .inCloud }
        if transcriptURL != nil { return .transcript }
        if hasMicAudio || hasSystemAudio { return .audioOnly }
        return .empty
    }

    /// Cheap full-text search across title, body, summary, and
    /// tag — so "mediacube" in the search box finds every session
    /// tagged with that name, even when the body doesn't mention
    /// the brand name.
    ///
    /// NB: `SessionStore.sessionsMatching` uses an inverted index as a
    /// candidate prefilter before calling this. If you add a field
    /// here, add it to `SessionStore.searchableFields(of:)` (and
    /// `searchStamp(of:)`) too, or the index will drop true matches.
    func matches(query: String) -> Bool {
        guard !query.isEmpty else { return true }
        let q = query.lowercased()
        if title.lowercased().contains(q) { return true }
        if tag.lowercased().contains(q) { return true }
        if transcriptText.lowercased().contains(q) { return true }
        if let s = summary {
            if s.summary.lowercased().contains(q) { return true }
            if s.actionItems.contains(where: { $0.lowercased().contains(q) }) { return true }
            if s.clientFollowUp.lowercased().contains(q) { return true }
        }
        return false
    }
}

// MARK: - Frontmatter parser

nonisolated private struct ParsedFrontmatter {
    var title: String?
    var locale: String?
    var started: String?
    var durationSec: Int?
    var folder: String?
    /// `daisy_kind:` — "recording" | "note". Nil for sessions saved
    /// before the note/recording split; `parseSession` then infers it.
    var kind: String?
    var tag: String?
    var attendees: [String] = []
    /// Attendee emails parsed from `daisy_event_emails`. Parallel to
    /// `attendees` (names) but a separate identity key. Empty when the
    /// session predates 1.0.7.10 or had no event emails.
    var attendeeEmails: [String] = []
    /// Title of the calendar event this session was bound to at
    /// start time, if any. Used by SessionDetailView to label the
    /// attendee picker so the user can verify "these are attendees
    /// from THIS event" — a tester reported seeing what looked like
    /// emails from a different meeting, which turned out to be the
    /// case where the wrong event was bound at session-start; the
    /// picker had no header naming the source.
    var linkedEventTitle: String?
    var speakerMap: [String: String] = [:]
    /// `"ok"` / `"empty"` / nil — see StoredSession.systemAudioStatus.
    var systemAudioStatus: String?
    /// `daisy_mic_only:` — raw `MicOnlyCause` value, or nil.
    var micOnlyCause: String?
    /// Markdown body after the closing `---`. Empty if no frontmatter.
    var body: String
}

nonisolated private func parseFrontmatter(in markdown: String) -> ParsedFrontmatter {
    var parsed = ParsedFrontmatter(body: markdown)
    let lines = markdown.split(separator: "\n", omittingEmptySubsequences: false)
    guard lines.first?.trimmingCharacters(in: .whitespaces) == "---" else {
        return parsed
    }
    // Find the closing "---".
    var closeIdx: Int?
    for i in 1..<lines.count {
        if lines[i].trimmingCharacters(in: .whitespaces) == "---" {
            closeIdx = i
            break
        }
    }
    guard let endIdx = closeIdx else { return parsed }

    for i in 1..<endIdx {
        let line = String(lines[i])
        guard let colonIdx = line.firstIndex(of: ":") else { continue }
        let key = line[..<colonIdx].trimmingCharacters(in: .whitespaces)
        var valueRaw = line[line.index(after: colonIdx)...].trimmingCharacters(in: .whitespaces)
        // Strip surrounding quotes.
        if valueRaw.hasPrefix("\"") && valueRaw.hasSuffix("\"") && valueRaw.count >= 2 {
            valueRaw = String(valueRaw.dropFirst().dropLast())
        }
        switch key {
        case "title":         parsed.title = valueRaw
        case "locale":        parsed.locale = valueRaw
        case "started":       parsed.started = valueRaw
        case "duration_sec":  parsed.durationSec = Int(valueRaw)
        case "daisy_folder":  parsed.folder = valueRaw.lowercased()
        case "daisy_kind":    parsed.kind = valueRaw.lowercased()
        case "daisy_tag":     parsed.tag = valueRaw
        // Legacy alias — sessions saved by 1.0.5 had `daisy_client:`
        // before we renamed the field. Read but don't write; the
        // upsertFrontmatter call in setTag will replace the line
        // with the new key on the next edit.
        case "daisy_client":
            if parsed.tag == nil { parsed.tag = valueRaw }
        case "daisy_event_attendees":
            parsed.attendees = parseYAMLArray(valueRaw)
        case "daisy_event_emails":
            parsed.attendeeEmails = parseYAMLArray(valueRaw)
        case "daisy_event_title":
            // YAML-quoted via MarkdownExporter.yamlQuote; strip the
            // surrounding double quotes for display.
            parsed.linkedEventTitle = yamlUnquote(valueRaw)
        case "daisy_speaker_map":
            parsed.speakerMap = parseYAMLDict(valueRaw)
        case "daisy_system_audio_status":
            parsed.systemAudioStatus = valueRaw
        case "daisy_mic_only":
            parsed.micOnlyCause = valueRaw
        default:              break
        }
    }
    let body = lines[(endIdx + 1)...].joined(separator: "\n")
    parsed.body = body
    return parsed
}

/// Strip surrounding double quotes from a YAML scalar value. The
/// frontmatter writer (`MarkdownExporter.yamlQuote`) wraps strings
/// in `"..."` to handle commas, colons, and bracket chars safely.
/// For display we want the raw text back.
nonisolated private func yamlUnquote(_ raw: String) -> String {
    let trimmed = raw.trimmingCharacters(in: .whitespaces)
    guard trimmed.hasPrefix("\""), trimmed.hasSuffix("\""), trimmed.count >= 2 else {
        return trimmed
    }
    return String(trimmed.dropFirst().dropLast())
        // yamlQuote escapes embedded "→\" — undo for display.
        .replacingOccurrences(of: "\\\"", with: "\"")
}

/// Parse a YAML-style inline array — `["Alex", "Maria", "Boris"]`.
/// Tolerant: ignores quotes, trims whitespace, drops empties.
nonisolated private func parseYAMLArray(_ raw: String) -> [String] {
    var trimmed = raw.trimmingCharacters(in: .whitespaces)
    if trimmed.hasPrefix("["), trimmed.hasSuffix("]") {
        trimmed = String(trimmed.dropFirst().dropLast())
    }
    return trimmed
        .split(separator: ",")
        .map { item in
            var s = item.trimmingCharacters(in: .whitespaces)
            if s.hasPrefix("\""), s.hasSuffix("\""), s.count >= 2 {
                s = String(s.dropFirst().dropLast())
            }
            return s
        }
        .filter { !$0.isEmpty }
}

/// Parse a YAML-style inline dict — `{A: "Alex", B: "Maria"}`.
/// Internal rather than file-private: the post-stop pipeline reads the
/// `daisy_speaker_map:` line back out of `transcript.md` to see renames
/// the user made while it was still running, and a second copy of this
/// parser would be a second place for the encoding to drift.
nonisolated func parseYAMLDict(_ raw: String) -> [String: String] {
    var trimmed = raw.trimmingCharacters(in: .whitespaces)
    if trimmed.hasPrefix("{"), trimmed.hasSuffix("}") {
        trimmed = String(trimmed.dropFirst().dropLast())
    }
    var out: [String: String] = [:]
    for pair in trimmed.split(separator: ",") {
        guard let colon = pair.firstIndex(of: ":") else { continue }
        let key = String(pair[..<colon]).trimmingCharacters(in: .whitespaces)
        var value = String(pair[pair.index(after: colon)...]).trimmingCharacters(in: .whitespaces)
        if value.hasPrefix("\""), value.hasSuffix("\""), value.count >= 2 {
            value = String(value.dropFirst().dropLast())
        }
        if !key.isEmpty, !value.isEmpty {
            out[key] = value
        }
    }
    return out
}
